#!/bin/sh

#Setting swapsize and swappiness
#ZRAM_DISKSIZE=`getprop zram.disksize 64`
#ZRAM_SWAPPINESS=`getprop sys.vm.swappiness 100`

. /etc/formfactor/config

#select lz4 compression algorithm
echo lz4 > /sys/block/zram0/comp_algorithm

echo $(($ZRAM_DISKSIZE*1024*1024)) > /sys/block/zram0/disksize

#mknod /dev/block/zram0 b 253 0
mkswap /dev/zram0
swapon /dev/zram0
echo $((ZRAM_SWAPPINESS)) > /proc/sys/vm/swappiness

#Enable enhance meminfo
echo 1 > /sys/module/emem/parameters/enable

#Set vmpressure based process reclaim
echo 1 > /sys/module/process_reclaim/parameters/enable_process_reclaim
