CONFIG_SPRD_FIREWALL = "true"
TRUSTY_PRODUCTION_VERSION = "2"

SML_TARGET_DTB_PATH = "${OEROOT}/source/kernel/kernel5.4/arch/arm64/boot/dts/sprd/sp9863a.dts"
SML_TARGET_DTBO_PATH = "${OEROOT}/layers/meta-unisoc/recipes-kernel/linux/linux-unisoc-5.4/s9863a/sp9863a-1h10-otadev-overlay.dts"
TOS_TARGET_DTS = "${OEROOT}/source/kernel/kernel5.4/arch/arm64/boot/dts/sprd/sp9863a.dts"

GLP_PROJECT = "true"
