CONFIG_SPRD_FIREWALL = "true"
TRUSTY_PRODUCTION_VERSION = "2"

SML_TARGET_DTB_PATH = "${OEROOT}/source/kernel/kernel5.4/arch/arm64/boot/dts/sprd/ums9620.dts"
SML_TARGET_DTBO_PATH = "${OEROOT}/layers/meta-unisoc/recipes-kernel/linux/linux-unisoc-5.4/ums9620/ums9620-2h10-otaab-overlay.dts"
TOS_TARGET_DTS = "${OEROOT}/source/kernel/kernel5.4/arch/arm64/boot/dts/sprd/ums9620.dts"

UFS_INLINE_CRYPTO = "true"
SUPPORT_DVFS_LOGIC = "true"

GLP_PROJECT = "true"
