#!/bin/sh
DESC="sprdstorage"

do_start() {
	echo "Starting $DESC"
	/bin/mkdir -p /mnt/data/sprd_tee_ss/
	/usr/bin/sprdstorage -f teens -d /dev/trusty-ipc-dev0 -p /mnt/data/sprd_tee_ss &
}

do_stop() {
	start-stop-daemon --stop --name sprdstorage --quiet
}

case "$1" in
  start)
	do_start
	;;
  stop)
	echo "Stopping $DESC"
	do_stop
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	do_stop
	sleep 1
	do_start
	;;
  *)
	echo "Usage: $0 {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0

